### PR TITLE
Set remote access via command line option

### PR DESCRIPTION
**Pull request by iercan**
There is `--bind-all` command line option to enable remote access on startup. That way we don't need to use supervisor and make thing more complicated. In addition, previous method was problematic with swarm deployments via portainer. I believe this PR will also solve it. 

I also added the HTTP_PORT env value to set the desired port in the container and EXTRA_FLAGS to provide any option mentioned in below document

https://docs.acestream.net/developers/engine-command-line-options/

### CODE REVIEW

**Review by martinbjeldbak — APPROVED** [review]
looks much simpler!

**Comment by martinbjeldbak** [comment]
This looks great, thank you for submitting another awesome PR @iercan after finding this command line option

**Comment by martinbjeldbak** [comment]
Published as [v2.3.](https://github.com/martinbjeldbak/acestream-http-proxy/releases/tag/v2.3.0)

**Comment by bijfy** [comment]
@iercan Hi, how can i use EXTRA_FLAGS . should it be in environment variable section and for example it can be like - EXTRA_FLAGS='quality' ? if not please provide extra info . thanks

**Comment by iercan** [comment]
> @iercan Hi, how can i use EXTRA_FLAGS . should it be in environment variable section and for example it can be like - EXTRA_FLAGS='quality' ? if not please provide extra info . thanks

Refer to the options in the link below:  
https://docs.acestream.net/developers/engine-command-line-options/  

For example:  

`EXTRA_FLAGS=--cache-limit=10`

**Pull request merged**
