### PR TITLE
Add pychromecast to the image

### LINKED ISSUE #27: Compatibility TVHeadend
There are no problems playing these links with vlc. But I was wondering if there is a way to add them to tvheadend.

### PR DESCRIPTION
**Pull request by iercan**
Aiming to resolve #27. Unable to test it myself; we need validation from @Euskalgaming.

### CODE REVIEW

**Comment by martinbjeldbak** [comment]
You're on fire @iercan. I'll publish an RC tag and we can test

**Review by martinbjeldbak — APPROVED** [review]

**Comment by martinbjeldbak** [comment]
Released as [v2.4.0-rc.1](https://github.com/martinbjeldbak/acestream-http-proxy/releases/tag/v2.4.0-rc.1)

**Comment by iercan** [comment]
@martinbjeldbak I think you can release this as stable.

**Comment by martinbjeldbak** [comment]
hey @iercan, happy to. I'm just weary of bloating the image with another dependency. are we confident it's working?

**Comment by iercan** [comment]
In the issue, @Euskalgaming confirmed the error about chromecast is gone

**Pull request merged**
